import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import DataContextProvider from "@/src/contexts/DataProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Desafio Mission Brasil",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} h-full`} // Adicionando a classe 'h-full' no body
				suppressHydrationWarning={true}
			>
				<DataContextProvider>
					<div className="bg-gray-100 h-full">{children}</div>{" "}
					{/* Definindo a altura 100% */}
				</DataContextProvider>
			</body>
		</html>
	);
}
